language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - nightly

services:
  - redis-server

install:
  - pip install -U pip setuptools
  - pip install -U -e ".[dev]"

script:
  - make test
